# Generated by Django 3.0.4 on 2020-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profs_teaching',
            field=models.ManyToManyField(related_name='all_courses_taught', to='professors.Professor'),
        ),
    ]
