# Generated by Django 3.0.4 on 2020-03-21 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_rating',
            name='liked_by',
            field=models.ManyToManyField(related_name='all_liked_courserating', to=settings.AUTH_USER_MODEL),
        ),
    ]
