# Generated by Django 3.0.4 on 2020-03-22 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_rating',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
