# Generated by Django 3.0.4 on 2020-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_rating_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_rating',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
