# Generated by Django 3.0.4 on 2020-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_rating_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_rating',
            name='last_reported_time',
            field=models.DateTimeField(default=None),
        ),
    ]
