# Generated by Django 3.0.4 on 2020-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_rating',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
