# Generated by Django 3.0.4 on 2020-03-21 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0002_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_rating',
            name='liked_by',
            field=models.ManyToManyField(related_name='all_liked_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
