# Generated by Django 3.0.4 on 2020-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_prof_rating_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_rating',
            name='last_reported_time',
            field=models.DateTimeField(default=None),
        ),
    ]
