# Generated by Django 3.0.4 on 2020-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_prof_rating_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='respect_points',
            field=models.IntegerField(default=0),
        ),
    ]
