# Generated by Django 3.0.4 on 2020-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_prof_rating_last_reported_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_rating',
            name='last_reported_time',
            field=models.DateTimeField(default=False),
        ),
    ]
